---
- hosts: web
  sudo: yes
  gather_facts: no
  remote_user: vagrant

  tasks:

  - name: install ssh key
    authorized_key: user=vagrant 
                    key="{{ lookup('file', '~/.ssh/ansible.pub') }}" 
                    state=present
