---

- name: Add Nginx Repository
  apt_repository: repo='ppa:ondrej/php5-5.6' state=present
  sudo: yes
  register: nginxrepoAdded

- name: Install nginx
  sudo: yes
  apt: pkg={{item}} state=latest update_cache=true
  with_items:
     - python-software-properties
     - nginx-common
     - nginx
     - php5-fpm
  when: nginxrepoAdded|success
  notify:
    - Reload Nginx