---

# file: webservers.yml
- hosts: web

  vars:
    apache_vhosts:
      - {servername: "example.local", documentroot: "/web/example/"}


  roles:
    - apache #only this install all needed for apache-php server
    #- nginx #only this install all needed for nginx-php server
    #- php56
    #- mysql
    #- nodejs
