---

# file: webservers.yml
- hosts: web

  vars:
    apache_vhosts:
      - {servername: "example.local", documentroot: "/web/example/"}
    mysql_dbs:
      - name: db1
        encoding: utf8
        collation: utf8_general_ci

  roles:
    - apache #only this install all needed for apache-php server
    #- nginx #only this install all needed for nginx-php server
    #- php56
    - mysql
    #- nodejs
